### ISSUE TITLE
Examples of current processes

### ISSUE THREAD

**Issue by oliverjam** [oliverjam/mentor-match#8]
@beardfacebo do we have any way of seeing how the current development plan creation process happens? Is there a form that is filled in with the advisor? Noga suggested that it would be good to see what we're replacing.

**Comment by beardfacebo** [comment]
At the moment it is very ad-hoc and a formal process hasn't been implemented, the recording maps directly on to what we spoke about Saturday. Goal and work out how to get there.

I know in other services they are asked to think of PD goals, narrow down to one and think about how they're going to get there, what they need to get there, and who will help them. Is that any clearer?
